### PR TITLE
Add desktop client using Dioxus

### PR DESCRIPTION
**Pull request by StyMaar**
Run with

```
RUSTFLAGS="-C target-cpu=native" RUST_BACKTRACE=1 cargo run --release --bin=desktop --features=desktop
```

### CODE REVIEW

**Comment by samuel-vitorino** [comment]
Thank you so much for this, as it is a requested feature. Some things I noticed (at least on my end):

- The text message box doesn't stay on bottom so a longer conversation just scrolls the input out of the screen.
- Enter key doesn't send.
- Message doen't clear on send.
- No darkmode option. 

If those are easy to fix, I will wait for those changes, if not, i will merge as is, as it is still super useful. 

PS: update on the other pull requests: I'm currently adding support  for PHI3.5-mini and vision (multimodal), so for now I don't want to change the rest of the code. After that I will check it out.

**Comment by StyMaar** [comment]
Thanks for the feedback.

> Enter key doesn't send.

It was thought as a feature actually, it's ctrl-enter to send (like groq's playground that I'm using a lot). I can change it to “Enter to send/ shit+Enter for new line” like ChatGPT if you prefer.

> Message doesn't clear on send.

I noticed that one but forgot to fix it before the PR, I'll fix in this PR tonight.

> No darkmode option.

Yeah I made the most minimal working version, didn't want to spend to much time on it without knowing if you'd be interested by the PR ^^. I can add it in another PR in a few days.

> The text message box doesn't stay on bottom so a longer conversation just scrolls the input out of the screen.

You'd like it to stay a the bottom of the screen even if you need to scroll to read the answer, do I understand correctly?

**Comment by samuel-vitorino** [comment]
> It was thought as a feature actually, it's ctrl-enter to send (like groq's playground that I'm using a lot). I can change it to “Enter to send/ shit+Enter for new line” like ChatGPT if you prefer.

I guess it's nice that way, don't change it.

> Yeah I made the most minimal working version, didn't want to spend to much time on it without knowing if you'd be interested by the PR ^^. I can add it in another PR in a few days.

If it's too much work don't worry about it!

> You'd like it to stay a the bottom of the screen even if you need to scroll to read the answer, do I understand correctly?

Just like the web version, the message input box with the send icon should be fixed at the footer, the part that scrolls is the chat messages. Right now the input box scrolls with the chat messages. When there are no chat messages the box stays at the top of the screen and when there are more messages you have to scroll down to the bottom to send another one. If you see here (https://samuel-vitorino.github.io/lm.rs-webui/), the message input is on the bottom even if there are no messages.

Thanks again!

**Comment by StyMaar** [comment]
> If it's too much work don't worry about it!

It's not that much work, and I also want to add the crab “profile picture” + the typewriter effect.

> Just like the web version, the message input box with the send icon should be fixed at the footer, the part that scrolls is the chat messages.

Thanks for the clarification, I'll fix that when I got back to the gui.

I fixed the input clearing bug, maybe you can merge this PR as it is right now, and I'll make another one for the changes above.

Now I'm trying to bring gpu acceleration with wgu compute shaders (since I'm a complete noob in graphics programming I'm still struggling but I wanted an excuse to try dioxus and learn compute shaders for a while and your project is a very good excuse for both =D)

**Comment by samuel-vitorino** [comment]
Merged. I considered adding GPU support as well, but I realized it would significantly increase the project's complexity. Nevertheless, I'm excited to see what you’ll bring next!

**Comment by StyMaar** [comment]
Oops sorry, I didn't expect it to reach #1 of the HN front page.

Now I realize that it's kind of rude actually to have submitted it at all without asking you beforehand.

**Comment by samuel-vitorino** [comment]
Wow! It's nice seeing that much people interested on the project, right on time that I added multimodality with PHI-3.5 support :)

**Pull request merged**
